fix(connectivity.eligibility): rework on building details call api
ovh-ux/ovh-api-services pull request #317
Opened 2020-11-17 16:44 UTC by Steffy29

Resolve pending return on the call API

Ref: UXCT-323

Signed-off-by: Stephanie Moallic <stephanie.moallic@corp.ovh.com>

2020-11-18 07:50 UTC, JeremyDec approved these changes

2020-11-18 08:06 UTC, JeremyDec requested changes
Hello @Steffy29, your changes will breaks this logic: https://github.com/ovh/manager/blob/546b941c0d93e2cc286e24c81704b8a55f07de70/packages/manager/apps/telecom/src/app/telecom/pack/move/eligibility/address/move-eligibility-address.controller.js#L184 due to method name change

2020-11-19 12:58 UTC, Steffy29 commented
@JeremyDec I know it so I prepare the update of the code into the concerned components into PR https://github.com/ovh/manager/pull/4043.

2020-11-20 07:37 UTC, marie-j approved these changes

2020-11-20 08:36 UTC, antleblanc approved these changes

2020-11-20 08:37 UTC, merged